### ISSUE TITLE
Some suggestions on the codes

### ISSUE THREAD

**Issue by NeilKeats** [layerfMRI/LAYNII#15]
I have some suggestions on the codes:
**for the header file _LAYNII/dep/laynii_lib.h_**
1. An **include guard** might be helpful to avoid compile problem when there is double inclusion. [see here](https://stackoverflow.com/questions/1653958/why-are-ifndef-and-define-used-in-c-header-files)
2. `using namespace std;` is not suggested to be used in header files, beacuse the namespace might affect other files that include this header. Considering that the header file only uses two names  (**_string_** and **_tuple_**) that belongs to `_std_`. I think it's OK to remove `using namespace std;` and use the following names: `_std::string_` and `_std::tuple_` .  [see here](https://stackoverflow.com/questions/5849457/using-namespace-in-c-headers)
3. The two inclusion `#include <math.h>` and `#include < cmath>`might be duplicate and are not used in the header file. I think it's better to move one of it to the source file `laynii_lib.cpp` and remove another one.

4. **[for the source file _LAYNII/dep/laynii_lib.cpp_]** For integer types **_int32_t_** and **short**, there are no implementations of the function **_isnan_( )**. Hence my visual studio compilor fails to build the codes. I remove this judgement for integer types to solve the compilation problem. I think there is not nan value for integer types, but the conversion from  floating point types to integer types might lead to invalid values. I think there might be a more sophisticated method to judge whether the data value is valid.

**Comment by ofgulban** [comment]
Hi @NeilKeats ,

Thanks a lot for taking the time to provide your feedback. We appreciate this.

1.  Thanks for pointing this out.
2. We already had a few issues related to this (#12 ) and are planning to remove `using namespace std` in the future.
3. Thanks for highlighting this one too :)
4. We will look into this but if you find some alternative ways to check nans, do let us know. We are almost always developing on linux and mac using g++ so it is valuable for us to know when things go wrong when using other compilers and how to fix those while keeping things working for us. Again, much appreciated.

**Comment by layerfMRI** [comment]
4.) The isnan() indeed caused some issues before. Since NaN values have the odd property that comparisons involving them are always false, we could replace them with (foo != foo). This is only true for NaNs. We got rid of all of the remaining  isnsn() in laynii_lib.cpp, LN_IMAGIRO.cpp and  LN_MP2RAGE_DNOISE.cpp in version v1.5.6.

3.) We in fact did not use any functions in <cmath> , that are not already included in <math.h>. So we got rid of <cmath> in version v1.5.6. 

2.) Thanks for the tip.
Since I am still spending more time writing code than executing code, I feel it is appropriate to use namespace std and just live with the risk of affecting other files that use this header, for now? 
including all _std:: in all the files might be a task for the future, E.g., if (against all odds) this software will be used so much that the development time is less than the execution time.
