### ISSUE TITLE
Segmentation fault for 3D LN_GROW_LAYERS

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#23]
Since version v1.5.0 until 1.5.7, there are some data and some commands that give segmentation fault errors. 

One example is this command 
`LN_GROW_LAYERS -rim sc_rim.nii -N 1000 -vinc 50 -threeD`
on those data [here](https://drive.google.com/drive/folders/1nYfurf5H_fJWoEZjN8npQMvQd0Yk_LOc?usp=sharing): 

Version v.1.0 works without problems. 
Though, this program has not been reverted and the bug is currently in effect.

This issue refers to personal correspondence from April 17th.

**Comment by ym98-stack** [comment]
Hi, 

Thank you for the information. Is there a way to get around that? Like some special requirement for -rim.nii volume input? 

Many thanks,

Yixin

**Comment by ofgulban** [comment]
Hi @ym98-stack ,

You can use `LN2_LAYERS` as an alternative. If you can be more specific about your issue we can help further.

**Comment by ym98-stack** [comment]
Hi,

Thank you for your reply.

I tried to run the following three lines of code, the LN_GROW_LAYERS with -threeD seems to give segmentation error, but the LN_3DGROW_LAYERS and LN_GROW_LAYERS in 2-D works just fine. This makes me think that my rim.nii files must have some problems. (Maybe pial and white surfaces are not smooth enough in 3D?)

Ideally, I would like to run everything in 3D to make sure the layers are growing in the direction normal to the cortex. The reason that I cannot directly use LN_3DGROW_LAYERS is that, given the resolution of my image (0.45mm), 21 layers that automatically chosen in LN_3DGROW_LAYERS seems to be too many.  Is there a way to get around that?

I currently don’t have the newest version with LN2_LAYERS function, but I would like to try that as well.

/usr/local/packages/laynii/bin/LN_GROW_LAYERS -rim lh_all2_int16.nii -N 15 -thin, successful

/usr/local/packages/laynii/bin/LN_GROW_LAYERS -rim lh_all2_int16.nii -N 15 -threeD -thin, Segmentation error

/usr/local/packages/laynii/bin/LN_3DGROW_LAYERS -rim lh_all2_int16.nii, successful

Thank you for your help in advance,

Yixin Ma


On Oct 26, 2020, at 4:36 AM, Omer Faruk Gulban <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @ym98-stack<https://urldefense.com/v3/__https://github.com/ym98-stack__;!!OToaGQ!9CQJ8dlIcQUrEO7gZbIhzugHcT_ApYW1OV59VRy2ZZ5xnhtff5l4zwingTnMYwTJ$> ,

You can use LN2_LAYERS as an alternative. If you can be more specific about your issue we can help further.

**Comment by ofgulban** [comment]
Thanks for spending time on detailing the specific issues Yixin.

We have spent significant effort on improving our layering algorithm since February 2020. It will be to your benefit to use the latest version of LAYNII, and if possible try `LN2_LAYERS` in the long run. Could you let us know which version of LAYNII you are using?

**Comment by ofgulban** [comment]
With regards to your "21 layers being too many question", in `LN2_LAYERS` we output files called `metric`. These files provide the measured **normalized cortical depth** of each voxel (a value between 0 and 1). You can avoid deciding "how many layers to use" in other words "how to best quantize your cortical depths" by using making use of these metric files instead of using layers files.

**Comment by ym98-stack** [comment]
Thank you for the information! We are upgrading our LAYNII to the newest version. I’ll let you know if there is any problems.

I actually cannot figure out what version was the old version. I was not able to find any version related information stored in the file.

Cheers,

Yixin

On Oct 26, 2020, at 12:25 PM, Omer Faruk Gulban <notifications@github.com<mailto:notifications@github.com>> wrote:



With regards to your "21 layers being too many question", in LN2_LAYERS we output files called metric. These files provide the measured normalized cortical depth of each voxel (a value between 0 and 1). You can avoid deciding "how many layers to use" in other words "how to best quantize your cortical depths" by using making use of these metric files instead of using layers files.

**Comment by ofgulban** [comment]
Thanks. Then it must be pre-2020 LAYNII. You are better off updating it :)

Let us know if you have the same old troubles or new troubles with the new version.

**Comment by ofgulban** [comment]
Closing this issue now as the new `LN2_LAYERS` replaced the `LN_GROW_LAYERS`. Feel free to re-open if this assessment is incorrect.
