### ISSUE TITLE
LN_BOCO default output name issue

### ISSUE THREAD

**Issue by 27-apizzuti** [layerfMRI/LAYNII#32]
Hi! There is a problem with the function `LN_BOCO`: one of the output should have as default name `VASO_LN.nii`, but it does not happen and it is not possible to assign a different name using `-output` function.

**Comment by ofgulban** [comment]
Thanks @27-apizzuti for reporting this. I think the long term solution will be re-thinking the how the save nifti function works. In programs with multiple outputs (e.g. `LN_BOCO`), I think we should indicate that the `-output` is not directly the name of the resulting file but the 'basename' of the outputs which will be tagged with corresponding suffixes  (e.g. `<basename>_VASO`, `<basename>_BOLD_avg`, `<basename>_VASO_avg`...).

**Comment by layerfMRI** [comment]
I tested it too now. It nicely does add the right name to all the secondary outputs. 
The main output however, should not follow the conventional approach that it "adds" a prefix. 

The vast majority of users of LN_BOCO assume that the main output will be called VASO_LN.nii 
e.g. this [script](https://github.com/layerfMRI/repository/blob/master/afni_VASO_flex.sh) and all scripts that are used in video tutorials assume that the main output will be called VASO_LN.nii.

Thus, it would be great, if the default would be set in a way that the main output name is VASO_LN.nii. without any additional prefixes or suffixes. 

Right now, this output name cannot be chosen, even when the "-output" option is used. 

I think in Faruks writing function, this should be possible, right? Otherwise we could write it out manually?

**Comment by ofgulban** [comment]
Thanks for looking into this Renzo, I see what you mean. All side-outputs follow a basename but the main output should exactly have what is given in the `-output` option. I will look into this.

**Comment by layerfMRI** [comment]
Yes, if possible. I know that this is against the convention in all other LayNii programs. But anything else would confuse a lot of users. 
If you want the keep it consistent with the convention of all other LayNii programs, we might consider adding another option. E.g. -output_conventional? or something like this? 
Of course, we need to include the description of this in the little help text. I think we had it there for some releases?!?

**Comment by ofgulban** [comment]
I am leaning towards keeping the behavior as it was, but introducing a `-basename` flag to indicate that the main output will be suffixed.

**Comment by layerfMRI** [comment]
Sounds good to me. 
I understand it right as follows?
-> if there is no extra output flag given, the output of the main file will be VASO_LN.nii (default). 
-> if the -output flag is used, it will be used as a suffix additionally to the basename of the input file.

**Comment by ofgulban** [comment]
Yes, I think this should work.

**Comment by ofgulban** [comment]
@layerfMRI check out the changes and let me know if it works as desired.

**Comment by layerfMRI** [comment]
Perfect. Thanks a lot you two. 
This is exactly how I desired it. 
Highly appreciated

**Comment by kenshukoiso** [comment]
Since the LN_BOCO has a slightly different output name convention than the rest of the LayNii programs, it would make sense to explicitly mention this in the little 'help' menu of the program. 
E.g. include "if no output file name is specified, the output file name is VASO_LN.nii in the current folder."
Thanks
