### ISSUE TITLE
Getting layers in EPI space

### ISSUE THREAD

**Issue by giobattistella** [layerfMRI/LAYNII#47]
Hi,
I followed the steps described in https://layerfmri.com/2017/11/26/getting-layers-in-epi-space/ to extract layers from the MP2RAGE in the EPI space. Everything seemed to work fine till the transformation of pial surface from Freesurfer to volume with SUMA. It looks like that the pial rim is "scattered" in some portions of the brain, thus impeding the layering of the cortex. The WM rim looks fine instead. 
I am happy to share with you the data if those might help you understand better the problem I am having.

Best,
Giovanni

**Comment by layerfMRI** [comment]
Hi Giovanni, 

Yes, I think I know what you mean. You mean an artifact like this?
![missing_voxels_artifact](https://user-images.githubusercontent.com/33968961/141774221-43f59c6d-11a1-4668-a2cb-8ab6522ebb7d.gif)
(artifact from @kenshukoiso)
This is a feature of working in vertex space. It suggests that the vertex density is not high enough to capture all voxels. 
If you increase the vertex density, this effect will be reduced.
E.g. for the `MapIcosahedron` command, you can use the option  `-ld 2000`. Note that this will increase the file size of the surfaces.

Note that the blog post that you are referring to is from 2017. LayNii has improved quite a bit since then.
I would recommend you to use the new program `LN2_LAYERS` instead in step 5. 

Best regards, 
Renzo

**Comment by ofgulban** [comment]
@giobattistella , what is your progress on this issue? It would be useful if you can let us know whether your issue is solved. Thanks in advance.

**Comment by giobattistella** [comment]
Hi everybody,
I am really sorry for the delay in getting back to you but I had to work urgently on something else in the past weeks. As Renzo suggested, increasing the vertex density improves the results. I tried with -ld1200 and the results are better than my original attempt at -ld564 but still not good enough. The problem that I have is that when I try -ld2000 the command crashes; I got the message "Killed" and not outputs are stored.  Could this be due to the size of the output files that should be written? Do you have any ideas on how to solve this problem? thanks a lot for our help.

**Comment by ofgulban** [comment]
This sounds like a freesurfer problem therefore out of scope for us. If @layerfMRI does not have any suggestions I will close the topic.

**Comment by ofgulban** [comment]
Closing due to no response. Feel free to reopen in the future.
