### ISSUE TITLE
Issue in test.sh: invalid option

### ISSUE THREAD

**Issue by jbteves** [layerfMRI/LAYNII#49]
Hi LAYNII folks, great package! I tried running the `test.sh` file as packaged on MacOS 10.15, built from cloning the repo, and most tests completed but after "LN2_LAYERDIMENSION" reads "Finished," I receive an error:
```
** invalid option, '-mean_thresh'
```
I assume this happens in the final line of the test script,
```
../LN2_MASK -scores lo_BOLD_act.nii.gz -columns lo_columns.nii.gz -mean_thresh 1 -output mask.nii.gz -abs
```

**Comment by layerfMRI** [comment]
Thanks Joshua, 

This is a holdover from previous versions and wasn't considered then homogenising the name of the options. 
It should be `-mean_thr` instead of `-mean_thresh`.

This line is fixed in the devel branch now. the entire line reads:
`../LN2_MASK -scores lo_BOLD_act.nii.gz -columns lo_columns.nii.gz -mean_thr 1 -output mask.nii.gz -abs`

Thanks, 
Renzo
