### ISSUE TITLE
dicom to nifti

### ISSUE THREAD

**Issue by zqsha** [layerfMRI/LAYNII#79]
Hi experts,
We recently collected VASO-based fmri data. Generally, we got DICOM data (.IMA) from the scanner. The first step should be converting DICOM to NIFTI. However, when we use MRIcroGL to convert DICOM, it does not work, there is no output image. I am not sure whether LAYNII provides this option to convert DICOM to NIFTI. Thanks.
Best,
Cain

**Comment by layerfMRI** [comment]
Hi Cain,

This might be more a VASO question than a LayNii question. LayNii does not provide its own conversion tool. 

VASO versions that are older than Jun 2022, had an issue of sorting images by the dimension of sets. 
(See question 17 here: [FAQ ](https://layerfmri.com/2021/02/22/vaso_ve/). I think this is the issue that MRICroGL might have (I don't know this tool).
We have decided to solve this issue from the sequence side, rather than the analysis side.

You can request an updated version of VASO to include the [Mosaic VASO functor ](https://layerfmri.com/2022/05/27/hackathon22/), 
Alternatively, you use one of the workarounds explained in the FAQ.
 E.g. using isiaconv : https://github.com/layerfMRI/repository/blob/master/conv/conv_Kronbichler.sh
Using ncm2niix https://github.com/layerfMRI/repository/blob/master/conv/conv_CAMB.sh
Using DIMON from AFNI https://github.com/layerfMRI/repository/blob/master/conv/other_options.sh

I hope this helps.
Best regards, Renzo
