### ISSUE TITLE
Inquiry about Morphological Characteristics Calculation for Cortical Layers

### ISSUE THREAD

**Issue by Changwen-Wu** [layerfMRI/LAYNII#94]
Hi experts
I am currently involved in a project focusing on the morphological characteristics of brain cortical layers, I'm focusing on layer-specific features like curvature and thickness. From my understanding, in LayNII, these features seem to be calculated across the entire cortex. Is it possible to calculate them for each cortical layer separately?
Additionally, I have a related question. Given that the existing layer segmentation mainly relies on equi-distant or equi-volume approaches, I am concerned whether the morphological characteristics calculated based on such layering might reflect the methodology of layering rather than the brain's intrinsic features. Could this be a potential issue in interpreting our findings?
Any insights, advice, or pointers to resources that could help address these questions would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
changwen

**Comment by ofgulban** [comment]
Dear @Changwen-Wu ,

Thanks for your interest and good questions. I am going to give a few quick answers, please feel free to follow up.
- Have you seen this tutorial on curvature and thickness in LayNii LN2_LAYERS: https://www.youtube.com/watch?v=D2zCPmNnqo0 ? 
- You can see that thickness and curvature are computed for each voxel, therefore you can pool them in your layer definitions.
- I am not sure if I understand your second question clearly. The layer computations in LayNii are built on geometric principles (equivolume and equidistance) as you indicate. The equivolume principle particularly is currently the best model that we have which accounts for the curvature variations that does not indicate neurobiologically differently structured brain areas. I am not sure what you particularly mean by "brain's intrinsic features". You might be mixing "neurobilogical layer definitions of the cortex" with "geometric layer definitions". These are not competing models. The geometric layers are a way of inserting a reference frame, through which the neurobilogical layers can be understood and modeled further (e.g. in their development). In addition, it is well know that one of the solid intrinsic cortical feature is the equivolume principle. When you do not account for this principle, you run the risk of falsely delineating areal borders. I suggest you to read: Siegfried Thomas Bok's works (for instance a good starting point is: Consolini, J., Demirci, N., Fulwider, A., Hutsler, J.J., Holland, M.A., 2022. Bok’s equi-volume principle: Translation, historical context, and a modern perspective. Brain Multiphysics 3, 100057. https://doi.org/10.1016/j.brain.2022.100057 ) as a starting point.

I have found your questions quite intriguing though so please feel free to elaborate further on what you mean and clarify what the issue is in precise detail. Or ask further questions.

Looking forward to hear back,
Faruk

**Comment by Changwen-Wu** [comment]
Dear @ofgulban ,
I have an additional question. Could you advise on the appropriate range of original resolution for 7T MRI(and fMRI) data to ensure effective layer analysis in pratical? 

Best,
changwen

**Comment by ofgulban** [comment]
Dear @Changwen-Wu , if you are planning to use LayNii, we have developed and optimized our software for MRI brain images below 0.4 mm isotropic resolution. I normally work within 0.2 to 0.35 mm iso. range with anatomical data for in vivo and ex vivo human brains. For functional data, you can consider upsampling/resampling your statistical maps after you compute them in their original resolution and proceed with LayNii computations.

Let me know if you have further questions.

**Comment by Changwen-Wu** [comment]
Dear @ofgulban,

Thank you again for your valuable guidance. I currently don't have any additional questions, but I truly appreciate your offer to help should I need any further assistance in the future.

Best regards,
Changwen

**Comment by ofgulban** [comment]
Great, happy to hear. Good luck.
